### PR TITLE
Fix unclosed JDBC connections

### LINKED ISSUE #206: Too many Postgres connections error on GraphQL query
## Observed behavior

The following error message was shown in the staging UI during any GraphQL fetch:

```
Error fetching GTFS entities via GraphQL

- Exception while fetching data (/feed) : org.postgresql.util.PSQLException: FATAL: remaining connection slots are reserved for non-replication superuser connections ({"line":3,"column":3})
```

This may be a configuration error for the staging server's postgres instance, but am logging it here because we may have something configured incorrectly in the connection pooling. cc @abyrd

**Update**: I just checked the # of connections with `select * from pg_stat_activity where datname = 'gtfs';` and found 97 rows.

## Expected behavior

GraphQL query should succeed.

## Steps to reproduce the problem

Go to an existing feed source and open the editor, or click the routes tab to trigger a GraphQL query.

## Any special notes on configuration used

N/A

## Version of datatools-server and datatools-ui if applicable (exact commit hash or branch name)

ui https://github.com/conveyal/datatools-ui/commit/544686bb3319a420371543461b98dd848229d833
server https://github.com/conveyal/datatools-server/commit/46d49ff7b647a817c211632eee5f048ed4f424d5

### PR DESCRIPTION
**Pull request by landonreed**
### Checklist

- [x] Appropriate branch selected _(all PRs must first be merged to `dev` before they can be merged to `master`)_
- [x] Any modified or new methods or classes have helpful JavaDoc and code is thoroughly commented
- [x] The description lists all applicable issues this PR seeks to resolve
- [x] The description lists any configuration setting(s) that differ from the default settings
- [x] All tests and CI builds passing

### Description

Fix instance where database connections are not being closed in gtfs-lib. Fixes #206, which has not appeared to be a source of problems in quite some time.

### CODE REVIEW

File: src/main/java/com/conveyal/gtfs/graphql/fetchers/FeedFetcher.java [hunk 1]
```diff
@@ -3,10 +3,12 @@
 import com.conveyal.gtfs.graphql.GTFSGraphQL;
 import graphql.schema.DataFetcher;
 import graphql.schema.DataFetchingEnvironment;
+import org.apache.commons.dbutils.DbUtils;
 import org.slf4j.Logger;
 import org.slf4j.LoggerFactory;
 
 import java.sql.Connection;
+import java.sql.PreparedStatement;
```
Comment (binh-dam-ibigroup) [inline src/main/java/com/conveyal/gtfs/graphql/fetchers/FeedFetcher.java:11]: Remove the now unused `import java.sql.statement` (L15).

**Comment by evansiroky** [comment]
@landonreed, I went ahead and fixed the failing builds by modifying the travis.yml file. Hopefully that's ok with you.
