### PR TITLE
Fix schedule exceptions bug in DateListField

### LINKED ISSUE #214: Cannot create schedule exceptions
## Observed behavior

It appears that gtfs-lib cannot create a schedule exception with some custom dates listed.

## Expected behavior

Schedule exceptions should be able to be created.

## Steps to reproduce the problem

This problem was original observed in a [failing build](https://travis-ci.org/conveyal/datatools-server/builds/514466082?utm_source=github_status&utm_medium=notification) of the e2e tests in https://github.com/conveyal/datatools-server/pull/167. A failing test case has been created to reproduce the issue [in this branch](https://github.com/conveyal/gtfs-lib/tree/schedule-exceptions-issue).

## Notes on configuration and files required to reproduce the issue

This error occurs with empty or populated tables of the schedule exception table.

### PR DESCRIPTION
**Pull request by landonreed**
fixes #214

### Checklist

- [x] Appropriate branch selected _(all PRs must first be merged to `dev` before they can be merged to `master`)_
- [x] Any modified or new methods or classes have helpful JavaDoc and code is thoroughly commented
- [x] The description lists all applicable issues this PR seeks to resolve
- [x] The description lists any configuration setting(s) that differ from the default settings
- [x] All tests and CI builds passing

### Description

A change to the return value for `Field#validate` (from String to ValidateFieldResult) caused an issue for creating/updating schedule exceptions with values for the `dates` field. This fixes the validate function and adds a CRUD test for schedule exceptions.

### CODE REVIEW

File: src/test/java/com/conveyal/gtfs/loader/JDBCTableWriterTest.java [hunk 1]
```diff
@@ -327,12 +315,76 @@ public void canCreateUpdateAndDeleteRoutes() throws IOException, SQLException, I
...
+                                                                         scheduleExceptionDTOClass);
+
+        // make sure saved data matches expected data
+        assertThat(scheduleException.removed_service[0], equalTo(simpleServiceId));
+        ResultSet resultSet = getResultSetForId(scheduleException.id, scheduleExceptionTable, "removed_service");
+        while (resultSet.next()) {
+            String[] array = (String[]) resultSet.getArray(1).getArray();
+            for (int i = 0; i < array.length; i++) {
+                assertEquals(exceptionInput.removed_service[i], array[i]);
+
```
Comment (evansiroky) [inline src/test/java/com/conveyal/gtfs/loader/JDBCTableWriterTest.java]: Please remove extra line

File: src/test/java/com/conveyal/gtfs/loader/JDBCTableWriterTest.java [hunk 2]
```diff
@@ -327,12 +315,76 @@ public void canCreateUpdateAndDeleteRoutes() throws IOException, SQLException, I
...
+        ScheduleExceptionDTO updatedDTO = mapper.readValue(updateOutput, scheduleExceptionDTOClass);
+
+        // make sure saved data matches expected data
+        assertThat(updatedDTO.dates, equalTo(updatedDates));
+        ResultSet rs2 = getResultSetForId(scheduleException.id, scheduleExceptionTable, "dates");
+        while (rs2.next()) {
+            String[] array = (String[]) rs2.getArray(1).getArray();
+            for (int i = 0; i < array.length; i++) {
+                assertEquals(updatedDates[i], array[i]);
+
```
Comment (evansiroky) [inline src/test/java/com/conveyal/gtfs/loader/JDBCTableWriterTest.java]: Please remove extra line
