### PR TITLE
Validate calendar days

### LINKED ISSUE #294: MTC: Feed validation should check services apply to at least one day of the week.
## Observed behavior

DataTools is missing validation for having at least one of the days active in calendar.txt file.

## Expected behavior

This check is a requirement in the MTC 511 transit data guidelines.

## Steps to reproduce the problem

Upload [this feed](https://github.com/ibi-group/datatools-server/files/5283516/Livermore_Amador_Valley_Transit_Authority-Future.zip) to DataTools server running MTC extensions. Note that in `calendar.txt` there is a service with id `7` that applies to no day of the week.

After the feed is loaded, observe that no validation error is produced.

### PR DESCRIPTION
**Pull request by binh-dam-ibigroup**
### Checklist

- [x] Appropriate branch selected _(all PRs must first be merged to `dev` before they can be merged to `master`)_
- [x] Any modified or new methods or classes have helpful JavaDoc and code is thoroughly commented
- [x] The description lists all applicable issues this PR seeks to resolve
- [x] The description lists any configuration setting(s) that differ from the default settings
- [x] All tests and CI builds passing

### Description

This PR fixes #294. This PR requires MTC extensions enabled.

### CODE REVIEW

File: src/main/java/com/conveyal/gtfs/validator/MTCValidator.java [hunk 1]
```diff
@@ -39,6 +42,32 @@ public void validate() {
             validateFieldLength(trip, trip.trip_headsign, 120);
             validateFieldLength(trip, trip.trip_short_name, 50);
         }
+
+        // Validate that calendars apply to at least one day of the week.
+        for (Calendar calendar : feed.calendars) {
+            validateCalendarDays(calendar);
+        }
```
Comment (landonreed) [inline src/main/java/com/conveyal/gtfs/validator/MTCValidator.java:49]: I don't think this needs to be an MTC-specific validator. I think this should apply across the board. Sorry if that wasn't clear.

File: src/main/java/com/conveyal/gtfs/error/NewGTFSErrorType.java [hunk 2]
```diff
@@ -44,6 +44,9 @@
     ROUTE_UNUSED(Priority.HIGH, "This route is defined but has no trips."),
     SERVICE_NEVER_ACTIVE(Priority.MEDIUM, "A service code was defined, but is never active on any date."),
     SERVICE_UNUSED(Priority.MEDIUM, "A service code was defined, but is never referenced by any trips."),
+    SERVICE_WITHOUT_DAYS(Priority.MEDIUM, "At least one of the days of the week fields (Monday,\n" +
+        "Tuesday, Wednesday, Thursday, Friday, Saturday, Sunday) must have its value set to '1'\n" +
+        "for each service defined in 'calendars.txt'."),
```
Comment (landonreed) [inline src/main/java/com/conveyal/gtfs/error/NewGTFSErrorType.java:49]: I don't understand why there are new lines in this description string. Also, a slight revision to bring it in line with other error descriptions:

> A service defined in calendar.txt should be active on at least one day of the week. Otherwise, it should be omitted from this file.

File: src/main/java/com/conveyal/gtfs/validator/MTCValidator.java [hunk 3]
```diff
@@ -39,6 +42,32 @@ public void validate() {
...
+    }
+
+    /**
+     * Checks that a {@link Calendar} entity is applicable for at least one day of the week
+     * (i.e. at least one of the fields for Monday-Sunday is set to '1').
+     * @param calendar The {@link Calendar} entity to check.
+     * @return true if at least one field for Monday-Sunday is set to 1, false otherwise.
+     */
+    public boolean validateCalendarDays(Calendar calendar) {
+        boolean result = calendar.monday == 1
```
Comment (landonreed) [inline src/main/java/com/conveyal/gtfs/validator/MTCValidator.java:59]: variable name `result` is not very descriptive.

File: src/main/java/com/conveyal/gtfs/validator/MTCValidator.java [hunk 4]
```diff
@@ -39,6 +42,32 @@ public void validate() {
...
+            || calendar.tuesday == 1
+            || calendar.wednesday == 1
+            || calendar.thursday == 1
+            || calendar.friday == 1
+            || calendar.saturday == 1
+            || calendar.sunday == 1;
+
+        if (!result) {
+            if (errorStorage != null) registerError(calendar, SERVICE_WITHOUT_DAYS, "[Service applies to no day of the week.]");
```
Comment (landonreed) [inline src/main/java/com/conveyal/gtfs/validator/MTCValidator.java:68]: the badValue arg doesn't add any information here to the error description, so it should not be included.

File: src/test/java/com/conveyal/gtfs/GTFSTest.java [hunk 5]
```diff
@@ -489,6 +489,31 @@ public void canLoadFeedWithLongFieldValues () {
         );
     }
 
+    /**
+     * Tests that a GTFS feed with a service id without calendar days assigned
```
Comment (landonreed) [inline src/test/java/com/conveyal/gtfs/GTFSTest.java:493]: "calendar days" sounds to me like "dates". A better phrase would be "days of the week."

File: src/test/java/com/conveyal/gtfs/GTFSTest.java [hunk 6]
```diff
@@ -489,6 +489,31 @@ public void canLoadFeedWithLongFieldValues () {
...
+     * (i.e. when 'monday' through 'sunday' fields are set to zero)
+     * generates a validation error per MTC guidelines.
+     */
+    @Test
+    public void canLoadFeedWithServiceWithoutDays() {
```
Comment (landonreed) [inline src/test/java/com/conveyal/gtfs/GTFSTest.java:498]: canLoadFeedWithServiceWithoutDaysOfTheWeek

File: src/test/java/com/conveyal/gtfs/validator/MTCValidatorTest.java [hunk 7]
```diff
@@ -10,19 +11,30 @@
 
 public class MTCValidatorTest {
     @Test
-    public void fieldlLengthShouldNotExceed() {
+    public void validateFieldLength() {
```
Comment (landonreed) [inline src/test/java/com/conveyal/gtfs/validator/MTCValidatorTest.java:14]: Maybe all the test names should begin with `can`.

**Review by landonreed — CHANGES_REQUESTED** [review]
Looking good, but I think the validation check should apply for all feeds (not just MTC).

File: src/main/java/com/conveyal/gtfs/error/NewGTFSErrorType.java (hunk 2 above)
Comment (binh-dam-ibigroup) [reply src/main/java/com/conveyal/gtfs/error/NewGTFSErrorType.java:49]: I pasted the text from the MTC guidelines, then IntelliJ split the lines automatically.

**Review by landonreed — APPROVED** [review]
Looks great, thanks!

File: src/main/java/com/conveyal/gtfs/validator/MTCValidator.java [hunk 8]
```diff
@@ -10,7 +10,8 @@
 
 /**
  * MTCValidator runs a set of custom validation checks for GTFS feeds managed by MTC in Data Tools.
- * The checks consist of validating field lengths at this time per the 511 MTC guidelines at
+ * At this time, the checks consist of validating field lengths and that calendars apply to
+ * at least one day of the week per the 511 MTC guidelines at
```
Comment (landonreed) [inline src/main/java/com/conveyal/gtfs/validator/MTCValidator.java:14]: Oops, one mistake found ^^. Comment above needs to have (statement about calendars removed).

Comment (binh-dam-ibigroup) [reply src/main/java/com/conveyal/gtfs/validator/MTCValidator.java]: Yep, just fixed.
